// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> funWithReturnCallback(
        {required FutureOr<String> Function(String) dartCallback}) =>
    RustLib.instance.api
        .crateApiRustManagerFunWithReturnCallback(dartCallback: dartCallback);

Future<void> funWithOnlyCallback(
        {required FutureOr<bool> Function(String) dartCallback}) =>
    RustLib.instance.api
        .crateApiRustManagerFunWithOnlyCallback(dartCallback: dartCallback);

Future<void> connectToNats(
        {required String endPoint,
        required FutureOr<void> Function(bool) onSuccess,
        required FutureOr<void> Function(String) onFailure}) =>
    RustLib.instance.api.crateApiRustManagerConnectToNats(
        endPoint: endPoint, onSuccess: onSuccess, onFailure: onFailure);

abstract class ConnectionCallback {
  Future<int> f({required String a});

  Future<void> onFailure({required String error});

  Future<void> onSuccess();
}
