// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> connectToNats(
        {required String endPoint,
        required FutureOr<void> Function(bool) onSuccess,
        required FutureOr<void> Function(String) onFailure}) =>
    RustLib.instance.api.crateApiRustManagerConnectToNats(
        endPoint: endPoint, onSuccess: onSuccess, onFailure: onFailure);

Future<void> sendRequest() =>
    RustLib.instance.api.crateApiRustManagerSendRequest();
